echo on

cd C:\DevDataflex\

del abc.dat
del abc1.dat
del apps.dat
del atrail.dat
del backup.dat
del backedup.dat
del case.dat
del cmdefend.dat
del cmoffens.dat
del cmrerv.dat
del CMServ.dat
del CMVictim.dat
del CMWitnes.dat
del Codemast.dat
del Codetype.dat
del Court.dat
del Crimhist.dat
del D.dat
del Data.dat
del Defend.dat
del Defnotes.dat
del Deposit.dat
del Docket.dat
del Fines.dat
del Image.dat
del JRNL.dat
del Judgex.dat
del Ledge.dat
del LukeFile.dat
del MastRpt.dat
del Net$Log.dat
del Offcode.dat
del Petition.dat
del Pktmp000.dat
del Pktmp001.dat
del Pktmp002.dat
del Prosamt.dat
del Proscutr.dat
del Queryold.dat
del Rechang1.dat
del Setbank.dat
del Sys.dat
del Tape_Def.dat
del Tape_Exc.dat
del TempJR.dat
del Test.dat
del Trans.dat
del Tri.dat
del TYJR.dat
del User1.dat
del Users.dat
del Userxold.dat
del Victim.dat

PAUSE